# Generated by Django 5.2.10 on 2026-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
