# Generated by Django 5.2.10 on 2026-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tour_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="max_people",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
